### ISSUE TITLE
dataset  bug

### ISSUE THREAD

**Issue by bobo0810** [yuecao0119/MMInstruct#1]
@yuecao0119  hello , caption_en.json image and caption misalignment, and there are some Chinese cases

**Comment by yuecao0119** [comment]
Thanks for your question.

But can you tell me which images don't match? I tried to access all the image paths in the json file and found no missing images.

It is worth noting that the path in our json file is similar to "image": "image_comparison/0001/00000053.jpg". You may need to modify it according to the actual path. For example, "**home/images/**"+"image_comparison/0001/00000053.jpg".
